@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Jan 15 12:04:56 +0300 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim structural_clk_divider_tb_behav -key {Behavioral:sim_1:Functional:structural_clk_divider_tb} -tclbatch structural_clk_divider_tb.tcl -view E:/BATUHAN DOSYALAR/ICTECH/devler/devlerim/structural_clk_divider_2/structural_clk_divider_tb_behav.wcfg -log simulate.log"
call xsim  structural_clk_divider_tb_behav -key {Behavioral:sim_1:Functional:structural_clk_divider_tb} -tclbatch structural_clk_divider_tb.tcl -view E:/BATUHAN DOSYALAR/ICTECH/devler/devlerim/structural_clk_divider_2/structural_clk_divider_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
