webtalk_init -webtalk_dir E:/BATUHAN DOSYALAR/ICTECH/devler/devlerim/ripple_carry_adder_4-bit/ripple_carry_adder_4-bit.sim/sim_1/behav/xsim/xsim.dir/ripple_carry_adder_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Dec 26 15:00:22 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4f566761-56e4-4c21-87db-4fa28862f525" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e086b244b83d4608ab03f1128c786e72" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6012_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3213905963 -regid "" -xml E:/BATUHAN DOSYALAR/ICTECH/devler/devlerim/ripple_carry_adder_4-bit/ripple_carry_adder_4-bit.sim/sim_1/behav/xsim/xsim.dir/ripple_carry_adder_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/BATUHAN DOSYALAR/ICTECH/devler/devlerim/ripple_carry_adder_4-bit/ripple_carry_adder_4-bit.sim/sim_1/behav/xsim/xsim.dir/ripple_carry_adder_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/BATUHAN DOSYALAR/ICTECH/devler/devlerim/ripple_carry_adder_4-bit/ripple_carry_adder_4-bit.sim/sim_1/behav/xsim/xsim.dir/ripple_carry_adder_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
