webtalk_init -webtalk_dir E:/BATUHAN DOSYALAR/ICTECH/devler/devlerim/different_clk_divider/different_clk_divider.sim/sim_1/behav/xsim/xsim.dir/counter_dif_clk_divider_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jan 10 00:37:29 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4f566761-56e4-4c21-87db-4fa28862f525" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cd7d56a7f06a406793e0d9816156b7f2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2440 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.23_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5992_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2048442467 -regid "" -xml E:/BATUHAN DOSYALAR/ICTECH/devler/devlerim/different_clk_divider/different_clk_divider.sim/sim_1/behav/xsim/xsim.dir/counter_dif_clk_divider_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/BATUHAN DOSYALAR/ICTECH/devler/devlerim/different_clk_divider/different_clk_divider.sim/sim_1/behav/xsim/xsim.dir/counter_dif_clk_divider_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/BATUHAN DOSYALAR/ICTECH/devler/devlerim/different_clk_divider/different_clk_divider.sim/sim_1/behav/xsim/xsim.dir/counter_dif_clk_divider_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
